/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "auto_test/s21_string_test.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "s21_sprintf/s21_sprintf.h"
#include "s21_string.h"

const char a[] = "Hello world";
const char b[] = "Hello world\n\0";
const char c[] = "a\n\0";
const char d[] = " \n\0";
const char e[] = " \0";
const char f[] = "\n\0";
const char g[] = "\0";

char buff[1000] = "";
char buff2[1000] = "";
char str[1000] = "Life is trying things to see if they work. -Ray Bradbury";

START_TEST(test_s21_strlen) {
  ck_assert_uint_eq(strlen(a), s21_strlen(a));
  ck_assert_uint_eq(strlen(b), s21_strlen(b));
  ck_assert_uint_eq(strlen(c), s21_strlen(c));
  ck_assert_uint_eq(strlen(d), s21_strlen(d));
  ck_assert_uint_eq(strlen(e), s21_strlen(e));
  ck_assert_uint_eq(strlen(f), s21_strlen(f));
  ck_assert_uint_eq(strlen(g), s21_strlen(g));
}
END_TEST

START_TEST(test_s21_strchr) {
  ck_assert_str_eq(strchr(a, 'l'), s21_strchr(a, 'l'));
  ck_assert(s21_strchr(a, 'n') == S21_NULL);
  ck_assert(s21_strchr(a, '\n') == S21_NULL);
  ck_assert_str_eq(strchr(e, ' '), s21_strchr(e, ' '));
}
END_TEST

START_TEST(test_s21_strcpy) {
  char b1[20];
  char b2[20];
  char b3[] = "aaaaaaaaaaaaaaaaaaaaaaaaaa";
  char b4[] = "aaaaaaaaaaaaaaaaaaaaaaaaaa";
  ck_assert_str_eq(strcpy(b1, a), s21_strcpy(b2, a));
  ck_assert_str_eq(strcpy(b3, a), s21_strcpy(b4, a));
}
END_TEST

START_TEST(test_s21_strcat) {
  char b1[20] = "a";
  char b2[20] = "a";
  char b3[50] = "lolkek";
  char b4[50] = "lolkek";
  ck_assert_str_eq(strcat(b1, a), s21_strcat(b2, a));
  ck_assert_str_eq(strcat(b3, "cheburek"), s21_strcat(b4, "cheburek"));
  char str1[21] = "TEST";
  char str2[8] = "strcat";
  char str3[9] = "function";
  char str4[1] = "";
  char str5[2] = " ";
  s21_strcat(str1, str5);
  ck_assert_msg(!memcmp(str1, "TEST ", 6), "1st strcat test failed");
  s21_strcat(str1, str2);
  ck_assert_msg(!memcmp(str1, "TEST strcat", 12), "2nd strcat test failed");
  s21_strcat(str1, str5);
  ck_assert_msg(!memcmp(str1, "TEST strcat ", 13), "3rd strcat test failed");
  s21_strcat(str1, str3);
  ck_assert_msg(!memcmp(str1, "TEST strcat function", 21),
                "4rth strcat test failed");
  s21_strcat(str1, str4);
  ck_assert_msg(!memcmp(str1, "TEST strcat function", 21),
                "5th strcat test failed");
}
END_TEST

START_TEST(test_s21_memcpy) {
  char b1[50] = {0};
  char b2[50] = {0};
  ck_assert_str_eq(memcpy(b1, a, 5), s21_memcpy(b2, a, 5));
  ck_assert_str_eq(memcpy(b1, e, 1), s21_memcpy(b2, e, 1));
  char *src1 = "schesrdsfdsfdsfesr";
  int len = s21_strlen(src1);
  char dest1[100] = {0};
  char dest2[100] = {0};
  char dest3[100] = {0};
  char dest4[100] = {0};
  char dest5[100] = {0};
  char dest6[100] = {0};
  char dest7[100] = {0};
  char dest8[100] = {0};
  char dest9[100] = {0};
  char dest10[100] = {0};
  s21_memcpy(dest1, src1, len + 1);
  memcpy(dest2, src1, len + 1);
  s21_memcpy(dest3, src1, 5);
  memcpy(dest4, src1, 5);
  s21_memcpy(dest5, src1, 0);
  memcpy(dest6, src1, 0);
  s21_memcpy(dest7, src1, 18);
  memcpy(dest8, src1, 18);
  s21_memcpy(dest9, src1, 1);
  memcpy(dest10, src1, 1);
  ck_assert_str_eq(dest1, dest2);
  ck_assert_str_eq(dest3, dest4);
  ck_assert_str_eq(dest5, dest6);
  ck_assert_str_eq(dest7, dest8);
  ck_assert_str_eq(dest9, dest10);
}
END_TEST

START_TEST(test_s21_memchr) {
  ck_assert_ptr_eq(memchr(a, 'e', 4), s21_memchr(a, 'e', 4));
  ck_assert_ptr_eq(memchr(a, 'd', 4), s21_memchr(a, 'd', 4));
  ck_assert_ptr_eq(memchr(e, 'd', 1), s21_memchr(e, 'd', 1));
  char *s1 = "This is a s21_memchr test";
  ck_assert_ptr_eq(s21_memchr(s1, 's', 0), memchr(s1, 's', 0));
  ck_assert_ptr_eq(s21_memchr(s1, 's', 2), memchr(s1, 's', 2));
  ck_assert_ptr_eq(s21_memchr(s1, 's', 20), memchr(s1, 's', 20));
  ck_assert_ptr_eq(s21_memchr(s1, 'u', 20), memchr(s1, 'u', 20));
  ck_assert_ptr_eq(s21_memchr(s1, 'u', 25), memchr(s1, 'u', 25));
}
END_TEST

START_TEST(test_s21_memcmp) {
  ck_assert(memcmp(a, a, 10) == s21_memcmp(a, a, 10));
  ck_assert(s21_memcmp(a, c, 3) < 0);
  ck_assert(s21_memcmp(c, a, 3) > 0);
  char *s1 = "This is a 1st string s21_memcmp test";
  char *s2 = "This is a 2nd string s21_memcmp test";
  ck_assert_msg(s21_memcmp(s1, s2, 36) == memcmp(s1, s2, 36),
                "1st memcmp test failed.");
  ck_assert_msg(s21_memcmp(s1, s2, 2) == memcmp(s1, s2, 2),
                "2nd memcmp test failed.");
  ck_assert_msg(s21_memcmp(s1, s2, 0) == memcmp(s1, s2, 0),
                "3rd memcmp test failed.");
}
END_TEST

START_TEST(test_s21_memset) {
  char b1[50] = "lolkek";
  char b2[50] = "lolkek";
  ck_assert_str_eq(memset(b1, '*', 8), s21_memset(b2, '*', 8));
  ck_assert_str_eq(memset(b1, '#', 3), s21_memset(b2, '#', 3));
  ck_assert_str_eq(memset(b1, '|', 1), s21_memset(b2, '|', 1));
}
END_TEST

START_TEST(test_s21_strncmp) {
  ck_assert(s21_strncmp(a, a, 10) == 0);
  ck_assert(s21_strncmp(a, c, 3) < 0);
  ck_assert(s21_strncmp(c, a, 3) > 0);
  ck_assert(s21_strncmp(f, g, 1) > 0);
}
END_TEST

START_TEST(test_s21_strstr) {
  ck_assert_str_eq(strstr(a, "llo"), s21_strstr(a, "llo"));

  ck_assert(s21_strstr(a, "\n") == S21_NULL);
  ck_assert_ptr_eq(strstr(e, "abc"),
                   s21_strstr(e, "abc"));  // must fail, so ptr_eq
}
END_TEST

START_TEST(test_s21_strcspn) {
  ck_assert_int_eq(strcspn(a, "Hel"), s21_strcspn(a, "Hel"));
  ck_assert_int_eq(strcspn(a, "llo"), s21_strcspn(a, "llo"));
  ck_assert_int_eq(strcspn(a, a), s21_strcspn(a, a));
  ck_assert_int_eq(strcspn(a, e), s21_strcspn(a, e));
}
END_TEST

START_TEST(test_s21_strtok_1) {
  char b1[25] = "test1/test2/test3/test4";
  char b2[25] = "test1/test2/test3/test4";
  char b3[24] = {'\0'};
  char b4[24] = {'\0'};
  ck_assert_str_eq(strtok(b1, "/"), s21_strtok(b2, "/"));
  ck_assert_str_eq(strtok(NULL, "/"), s21_strtok(NULL, "/"));
  ck_assert_str_eq(strtok(NULL, "/"), s21_strtok(NULL, "/"));
  ck_assert_str_eq(strtok(NULL, "/"), s21_strtok(NULL, "/"));
  ck_assert_str_eq(strtok(b1, "!"), s21_strtok(b2, "!"));
  ck_assert_ptr_eq(strtok(b3, "!"), s21_strtok(b4, "!"));  // ptr_eq
}
END_TEST

START_TEST(test_s21_strtok_6) {
  char str1[] = "++++++++";
  char str2[] = "++++++++";
  const char delims[] = "+_! =";

  char *got = s21_strtok(str1, delims);
  char *expected = strtok(str2, delims);

  ck_assert_ptr_null(got);
  ck_assert_ptr_null(expected);
}
END_TEST

START_TEST(test_s21_strtok_7) {
  char str1[] = "!       A!B!C!D!E!!F!!G";
  char str2[] = "!       A!B!C!D!E!!F!!G";
  const char delims[] = "+_! =";

  char *got = s21_strtok(str1, delims);
  char *expected = strtok(str2, delims);

  ck_assert_uint_eq(s21_strlen(got), s21_strlen(expected));
  ck_assert_str_eq(got, expected);

  while (got || expected) {
    got = s21_strtok(NULL, delims);
    expected = strtok(NULL, delims);

    if (got || expected) {
      ck_assert_str_eq(got, expected);
      ck_assert_uint_eq(s21_strlen(got), s21_strlen(expected));
    } else {
      ck_assert_ptr_null(got);
      ck_assert_ptr_null(expected);
    }
  }
}
END_TEST

START_TEST(test_s21_strncpy) {
  char b1[60] = "lolkek";
  char b2[60] = "lolkek";
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstringop-truncation"
  ck_assert_str_eq(strncpy(b1, a, 3), s21_strncpy(b2, a, 3));
  ck_assert_str_eq(strncpy(b1, b, 10), s21_strncpy(b2, b, 10));
  ck_assert_str_eq(strncpy(b1, c, 8), s21_strncpy(b2, c, 8));
#pragma GCC diagnostic pop
}
END_TEST

START_TEST(test_s21_strncat) {
  char b1[20] = "a";
  char b2[20] = "a";
  char b3[50] = "lolkek";
  char b4[50] = "lolkek";
  ck_assert_str_eq(strncat(b1, a, 5), s21_strncat(b2, a, 5));
  ck_assert_str_eq(strncat(b3, "cheburek", 8), s21_strncat(b4, "cheburek", 8));
}
END_TEST

START_TEST(test_s21_strrchr) {
  ck_assert_str_eq(strrchr(a, 'l'), s21_strrchr(a, 'l'));
  ck_assert_str_eq(strrchr(e, ' '), s21_strrchr(e, ' '));
}
END_TEST

START_TEST(test_s21_strpbrk) {
  ck_assert_str_eq(strpbrk(a, "llo"), s21_strpbrk(a, "llo"));
  ck_assert_str_eq(strpbrk(a, "aeiou"), s21_strpbrk(a, "aeiou"));
  ck_assert_str_eq(strpbrk(a, "et"), s21_strpbrk(a, "et"));
}
END_TEST

START_TEST(test_s21_strerror) {
#ifdef __APPLE__
  for (int i = 0; i != 108; i++) {
    ck_assert_str_eq(strerror(i), s21_strerror(i));
  }
#elif __linux__
  for (int i = 0; i != 134; i++) {
    ck_assert_str_eq(strerror(i), s21_strerror(i));
  }
#endif
}
END_TEST

START_TEST(to_upper) {
  char *s1 = "school-21";
  char *s2 = "School is Cool";
  char *s3 = "amogus";
  char *s4 = "Shrek is amogus";
  char *s5 = "what";
  char *r1 = s21_to_upper(s1);
  char *r2 = s21_to_upper(s2);
  char *r3 = s21_to_upper(s3);
  char *r4 = s21_to_upper(s4);
  char *r5 = s21_to_upper(s5);
  ck_assert_msg(!strcmp(r1, "SCHOOL-21"), "1st to_upper test failed");
  ck_assert_msg(!strcmp(r2, "SCHOOL IS COOL"), "2nd to_upper test failed");
  ck_assert_msg(!strcmp(r3, "AMOGUS"), "3rd to_upper test failed");
  ck_assert_msg(!strcmp(r4, "SHREK IS AMOGUS"), "4rth to_upper test failed");
  ck_assert_msg(!strcmp(r5, "WHAT"), "5th to_upper test failed");
  free(r1);
  free(r2);
  free(r3);
  free(r4);
  free(r5);
}
END_TEST

START_TEST(to_lower) {
  char s1[] = "SChOOl-21";
  char s2[] = "ScHool is CoOl";
  char s3[] = "amogus";
  char s4[] = "ShrEK is Amogus";
  char s5[] = "what";
  char *r1 = s21_to_lower(s1);
  char *r2 = s21_to_lower(s2);
  char *r3 = s21_to_lower(s3);
  char *r4 = s21_to_lower(s4);
  char *r5 = s21_to_lower(s5);
  ck_assert_msg(!strcmp(r1, "school-21"), "1st to_lower test failed");
  ck_assert_msg(!strcmp(r2, "school is cool"), "2nd to_lower test failed");
  ck_assert_msg(!strcmp(r3, "amogus"), "3rd to_lower test failed");
  ck_assert_msg(!strcmp(r4, "shrek is amogus"), "4rth to_lower test failed");
  ck_assert_msg(!strcmp(r5, "what"), "5th to_lower test failed");
  free(r1);
  free(r2);
  free(r3);
  free(r4);
  free(r5);
}
END_TEST

START_TEST(insert) {
  char *s1 = "School-21 test";
  char *s2 = "insert ";
  char *s3 = "amogus";
  char *s4 = "is";
  char *s5 = "shrek";
  char *res1 = s21_insert(s1, " ", 3);
  char *res2 = s21_insert(s5, s3, 5);
  char *res3 = s21_insert(s3, s5, 0);
  char *res4 = s21_insert(s5, s4, 5);
  char *res5 = s21_insert(s2, s1, 4);
  ck_assert_str_eq(res1, "Sch ool-21 test");
  ck_assert_str_eq(res3, "shrekamogus");
  ck_assert_str_eq(res5, "inseSchool-21 testrt ");
  free(res1);
  free(res2);
  free(res3);
  free(res4);
  free(res5);
}
END_TEST

START_TEST(test_s21_sscanf_d) {
  int a, a1;
  int b, b1;
  int c, c1, d, d1, e, e1;
  a = b = c = d = 1;
  a1 = b1 = c1 = d1 = 1;
  const char str[] = "-12345 -000456000 111 +0005 666 777";
  sscanf(str, "%3d %d %d %*d %d %2d", &a, &b, &c, &d, &e);
  s21_sscanf(str, "%3d %d %d %*d %d %2d", &a1, &b1, &c1, &d1, &e1);
  ck_assert_int_eq(a, a1);
  ck_assert_int_eq(b, b1);
  ck_assert_int_eq(c, c1);
  ck_assert_int_eq(d, d1);
  ck_assert_int_eq(e, e1);
}
END_TEST

START_TEST(test_s21_sscanf_s_and_c) {
  char a[40] = {'\0'}, c[40] = {'\0'}, d[40] = {'\0'};
  char b[40] = {'\0'};
  char a2[40] = {'\0'}, c2[40] = {'\0'}, d2[40] = {'\0'};
  wchar_t b2[40] = {'\0'};
  const char str[] = "lol kek cheburek morzh pisos";
  ck_assert_int_eq(sscanf(str, "%s %s %3c %*s %s", a, b, c, d),
                   s21_sscanf(str, "%s %s %3c %*s %s", a2, b2, c2, d2));
  ck_assert_str_eq(a, a2);
  ck_assert_str_eq(c, c2);
  ck_assert_str_eq(d, d2);
}
END_TEST

START_TEST(test_s21_sscanf_x) {
  int a1, b1, c1, d1, a2, b2, c2, d2;
  a1 = a2 = b1 = b2 = c1 = c2 = d1 = d2 = 1;
  const char str[] = "1778 012 0x1111 -10 pisos";
  int r1 = sscanf(str, "%x%x%x%x", &a1, &b1, &c1, &d1);
  int r2 = s21_sscanf(str, "%x%x%x%x", &a2, &b2, &c2, &d2);
  ck_assert_int_eq(r1, r2);
  ck_assert_int_eq(a1, a2);
  ck_assert_int_eq(b1, b2);
  ck_assert_int_eq(c1, c2);
  ck_assert_int_eq(d1, d2);
}
END_TEST

START_TEST(test_s21_sscanf_i) {
  int a1, b1, c1, d1, a2, b2, c2, d2;
  a1 = a2 = b1 = b2 = c1 = c2 = d1 = d2 = 1;
  const char str[] = "1778 012 0x1Aa8 -10 pisos";
  int r1 = sscanf(str, "%*i%i%i%i", &a1, &b1, &c1);
  int r2 = s21_sscanf(str, "%*i%i%i%i", &a2, &b2, &c2);
  ck_assert_int_eq(r1, r2);
  ck_assert_int_eq(a1, a2);
  ck_assert_int_eq(b1, b2);
  ck_assert_int_eq(c1, c2);
}
END_TEST

START_TEST(test_s21_sscanf_o) {
  int a1, b1, c1, d1, a2, b2, c2, d2;
  a1 = a2 = b1 = b2 = c1 = c2 = d1 = d2 = 1;
  const char str[] = "1775 012 0 -10 pisos";
  int r1 = sscanf(str, "%o%o%o%o", &a1, &b1, &c1, &d1);
  int r2 = s21_sscanf(str, "%o%o%o%o", &a2, &b2, &c2, &d2);
  ck_assert_int_eq(r1, r2);
  ck_assert_int_eq(a1, a2);
  ck_assert_int_eq(b1, b2);
  ck_assert_int_eq(c1, c2);
  ck_assert_int_eq(d1, d2);
}
END_TEST

START_TEST(test_s21_sscanf_n_and_percent) {
  int a1, b1, c1, d1, a2, b2, c2, d2;
  a1 = a2 = b1 = b2 = c1 = c2 = d1 = d2 = 1;
  const char str[] = "-12345 -000456000 111    0005 pisos";
  int r1 = s21_sscanf(str, "%d %d %n %d", &a1, &b1, &c1, &d1);
  int r2 = sscanf(str, "%d %d %n %d", &a2, &b2, &c2, &d2);
  ck_assert_int_eq(r1, r2);
  ck_assert_int_eq(a1, a2);
  ck_assert_int_eq(b1, b2);
  ck_assert_int_eq(c1, c2);
  ck_assert_int_eq(d1, d2);
}
END_TEST

START_TEST(test_s21_sscanf_f_and_e) {
  float a1, b1, a2, b2;
  float c1, c2;
  float d1, d2;
  a1 = a2 = b1 = b2 = c1 = c2 = d1 = d2 = 1.1;
  const char str[] = "-12345.445 12.34e+03 -0.0 1234e-03 pisos";
  s21_sscanf(str, "%f%f%f%f", &a1, &b1, &c1, &d1);
  sscanf(str, "%f%f%f%f", &a2, &b2, &c2, &d2);
  ck_assert_float_eq(a1, a2);
  ck_assert_float_eq(b1, b2);
  ck_assert_float_eq(c1, c2);
}
END_TEST

START_TEST(test_s21_sscanf_u) {
  unsigned int a1, b1, a2, b2;
  unsigned int c1, c2;
  unsigned int d1, d2;
  a1 = a2 = b1 = b2 = c1 = c2 = d1 = d2 = 1;
  const char str[] = "0 0002 -1 -1234 666 pisos";
  int r1 = sscanf(str, "%*u%u%u%u%u", &a1, &b1, &c1, &d1);
  int r2 = s21_sscanf(str, "%*u%u%u%u%u", &a2, &b2, &c2, &d2);
  ck_assert_int_eq(r1, r2);
  ck_assert_int_eq(a1, a2);
  ck_assert_int_eq(b1, b2);
  ck_assert_int_eq(c1, c2);
  ck_assert_int_eq(d1, d2);
}
END_TEST

START_TEST(clean_print) {
  sprintf(buff, " ");
  s21_sprintf(buff2, " ");
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_c) {
  sprintf(buff, "Life is %c long lesson in humility. -James M. Barrie", 'a');
  s21_sprintf(buff2, "Life is %c long lesson in humility. -James M. Barrie",
              'a');
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_d1) {
  int probs = 99;
  sprintf(buff, "I've got %d problems", probs);
  s21_sprintf(buff2, "I've got %d problems", probs);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_d2) {
  int probs = -99;
  sprintf(buff, "I've got %d problems", probs);
  s21_sprintf(buff2, "I've got %d problems", probs);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_d_plus1) {
  int probs = 99;
  sprintf(buff, "I've got %+d problems", probs);
  s21_sprintf(buff2, "I've got %+d problems", probs);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_d_plus2) {
  int probs = -99;
  sprintf(buff, "I've got %+d problems", probs);
  s21_sprintf(buff2, "I've got %+d problems", probs);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_d_space1) {
  int probs = 99;
  sprintf(buff, "I've got % d problems", probs);
  s21_sprintf(buff2, "I've got % d problems", probs);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_d_space2) {
  int probs = -99;
  sprintf(buff, "I've got % d problems", probs);
  s21_sprintf(buff2, "I've got % d problems", probs);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_u) {
  unsigned int ans = 42;
  sprintf(buff, "%u", ans);
  s21_sprintf(buff2, "%u", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_u_neg) {
  // negative test
  int ans = -42;
  ck_assert_int_eq(sprintf(buff, "%u", ans), s21_sprintf(buff2, "%u", ans));
}
END_TEST

START_TEST(sprintf_width) {
  int num = 78;
  sprintf(buff, "%6d", num);
  s21_sprintf(buff2, "%6d", num);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_width_2) {
  int num = 123;
  sprintf(buff, "%3d", num);
  s21_sprintf(buff2, "%3d", num);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_width_neg) {
  char *str = "stroka";
  sprintf(buff, "%6s", str);
  s21_sprintf(buff2, "%6s", str);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_flag_minus) {
  int min = 5;
  sprintf(buff, "%-6d", min);
  s21_sprintf(buff2, "%-6d", min);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_flag_plus) {
  int plus = 21;
  sprintf(buff, "%+d", plus);
  s21_sprintf(buff2, "%+d", plus);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_flag_zero) {
  int zero = 9;
  sprintf(buff, "%06d", zero);
  s21_sprintf(buff2, "%06d", zero);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_flag_space) {
  int space = 8;
  sprintf(buff, "%d", space);
  s21_sprintf(buff2, "%d", space);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_flag_procent) {
  int space = 8;
  sprintf(buff, "%% %d", space);
  s21_sprintf(buff2, "%% %d", space);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_flag_float) {
  float space = 6.9;
  sprintf(buff, "%f", space);
  s21_sprintf(buff2, "%f", space);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_flag_float_with_rounding) {
  float space = 6.96568981;
  sprintf(buff, "%f", space);
  s21_sprintf(buff2, "%f", space);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_prec) {
  int ans = 42;
  sprintf(buff, "%.6d", ans);
  s21_sprintf(buff2, "%.6d", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_char) {
  sprintf(buff, "%c", 'X');
  s21_sprintf(buff2, "%c", 'X');
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_char_with_width) {
  sprintf(buff, "%6c", 'X');
  s21_sprintf(buff2, "%6c", 'X');
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_char_with_width_and_minus) {
  sprintf(buff, "%-6c", 'X');
  s21_sprintf(buff2, "%-6c", 'X');
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_h_for_int) {
  short ans = 54;
  sprintf(buff, "%hd", ans);
  s21_sprintf(buff2, "%hd", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_int_precision_bigger_with) {
  int ans = 54;
  sprintf(buff, "%1.23d", ans);
  s21_sprintf(buff2, "%1.23d", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_uint_precision_bigger_with) {
  int ans = 54;
  sprintf(buff, "%1.25u", ans);
  s21_sprintf(buff2, "%1.25u", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_double_with_width_space) {
  float ans = 5.4;
  sprintf(buff, "%10f", ans);
  s21_sprintf(buff2, "%10f", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_double_with_width_zero) {
  float ans = 5.4;
  sprintf(buff, "%010f", ans);
  s21_sprintf(buff2, "%010f", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_double_with_minus) {
  float ans = 5.4;
  sprintf(buff, "%-10f", ans);
  s21_sprintf(buff2, "%-10f", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_string_with_width_space) {
  sprintf(buff, "%10s", "string");
  s21_sprintf(buff2, "%10s", "string");
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_string_with_width_and_minus) {
  sprintf(buff, "%-s", "string");
  s21_sprintf(buff2, "%-s", "string");
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_double_minus_25) {
  float ans = -0.05;
  sprintf(buff, "%f", ans);
  s21_sprintf(buff2, "%f", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_spec_int_minus_zero) {
  int ans = -0;
  sprintf(buff, "%d", ans);
  s21_sprintf(buff2, "%d", ans);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(sprintf_anya) {
  sprintf(buff, "test");
  s21_sprintf(buff2, "test");
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(octal) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 10;
  sprintf(buff, "%o", a);
  s21_sprintf(buff2, "%o", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(octal_width) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 10;
  sprintf(buff, "%10o", a);
  s21_sprintf(buff2, "%10o", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(octal_width_minus) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 10;
  sprintf(buff, "%-10o", a);
  s21_sprintf(buff2, "%-10o", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(octal_width_zero) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 10;
  sprintf(buff, "%010o", a);
  s21_sprintf(buff2, "%010o", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hex) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 177;
  sprintf(buff, "%X", a);
  s21_sprintf(buff2, "%X", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hex_width) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 177;
  sprintf(buff, "%10x", a);
  s21_sprintf(buff2, "%10x", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hex_width_minus) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 177;
  sprintf(buff, "%-10x", a);
  s21_sprintf(buff2, "%-10x", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hex_width_zero) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 177;
  sprintf(buff, "%010x", a);
  s21_sprintf(buff2, "%010x", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hexX) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 178;
  sprintf(buff, "%X", a);
  s21_sprintf(buff2, "%X", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hexX_width) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 178;
  sprintf(buff, "%10x", a);
  s21_sprintf(buff2, "%10x", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hexX_width_minus) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 178;
  sprintf(buff, "%-10x", a);
  s21_sprintf(buff2, "%-10x", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(hexX_width_zero) {
  char buff[1000] = "";
  char buff2[1000] = "";
  int a = 178;
  sprintf(buff, "%010x", a);
  s21_sprintf(buff2, "%010x", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(int_with_l) {
  long int a = 2147483647;
  sprintf(buff, "%ld", a);
  s21_sprintf(buff2, "%ld", a);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

START_TEST(string) {
  char buff[1000] = "";
  char str[10] = "string";
  char buff2[1000] = "";
  sprintf(buff, "%s", str);
  s21_sprintf(buff2, "%s", str);
  ck_assert_str_eq(buff, buff2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("functions");
  TCase *tc1_2 = tcase_create("sscanf_modificatiors");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_s21_strlen);
  tcase_add_test(tc1_1, test_s21_strchr);
  tcase_add_test(tc1_1, test_s21_strcpy);
  tcase_add_test(tc1_1, test_s21_strcat);
  tcase_add_test(tc1_1, test_s21_memcpy);
  tcase_add_test(tc1_1, test_s21_memchr);
  tcase_add_test(tc1_1, test_s21_memcmp);
  tcase_add_test(tc1_1, test_s21_memset);
  tcase_add_test(tc1_1, test_s21_strncmp);
  tcase_add_test(tc1_1, test_s21_strstr);
  tcase_add_test(tc1_1, test_s21_strcspn);
  tcase_add_test(tc1_1, test_s21_strtok_1);
  tcase_add_test(tc1_1, test_s21_strtok_6);
  tcase_add_test(tc1_1, test_s21_strtok_7);
  tcase_add_test(tc1_1, test_s21_strncpy);
  tcase_add_test(tc1_1, test_s21_strncat);
  tcase_add_test(tc1_1, test_s21_strrchr);
  tcase_add_test(tc1_1, test_s21_strpbrk);
  tcase_add_test(tc1_1, test_s21_strerror);
  tcase_add_test(tc1_1, to_upper);
  tcase_add_test(tc1_1, to_lower);
  tcase_add_test(tc1_1, insert);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, test_s21_sscanf_d);
  tcase_add_test(tc1_2, test_s21_sscanf_s_and_c);
  tcase_add_test(tc1_2, test_s21_sscanf_x);
  tcase_add_test(tc1_2, test_s21_sscanf_i);
  tcase_add_test(tc1_2, test_s21_sscanf_o);
  tcase_add_test(tc1_2, test_s21_sscanf_n_and_percent);
  tcase_add_test(tc1_2, test_s21_sscanf_f_and_e);
  tcase_add_test(tc1_2, test_s21_sscanf_u);
  tcase_add_test(tc1_2, clean_print);
  tcase_add_test(tc1_2, sprintf_spec_c);
  tcase_add_test(tc1_2, sprintf_spec_d1);
  tcase_add_test(tc1_2, sprintf_spec_d2);
  tcase_add_test(tc1_2, sprintf_spec_d_plus1);
  tcase_add_test(tc1_2, sprintf_spec_d_plus2);
  tcase_add_test(tc1_2, sprintf_spec_d_space1);
  tcase_add_test(tc1_2, sprintf_spec_d_space2);
  tcase_add_test(tc1_2, sprintf_spec_u);
  tcase_add_test(tc1_2, sprintf_spec_u_neg);
  tcase_add_test(tc1_2, sprintf_width);
  tcase_add_test(tc1_2, sprintf_width_2);
  tcase_add_test(tc1_2, sprintf_width_neg);
  tcase_add_test(tc1_2, sprintf_flag_minus);
  tcase_add_test(tc1_2, sprintf_flag_plus);
  tcase_add_test(tc1_2, sprintf_flag_zero);
  tcase_add_test(tc1_2, sprintf_flag_space);
  tcase_add_test(tc1_2, sprintf_flag_procent);
  tcase_add_test(tc1_2, sprintf_flag_float);
  tcase_add_test(tc1_2, sprintf_flag_float_with_rounding);
  tcase_add_test(tc1_2, sprintf_spec_prec);
  tcase_add_test(tc1_2, sprintf_spec_char);
  tcase_add_test(tc1_2, sprintf_spec_char_with_width);
  tcase_add_test(tc1_2, sprintf_spec_char_with_width_and_minus);
  tcase_add_test(tc1_2, sprintf_spec_h_for_int);
  tcase_add_test(tc1_2, sprintf_spec_int_precision_bigger_with);
  tcase_add_test(tc1_2, sprintf_spec_uint_precision_bigger_with);
  tcase_add_test(tc1_2, sprintf_spec_double_with_width_space);
  tcase_add_test(tc1_2, sprintf_spec_double_with_width_zero);
  tcase_add_test(tc1_2, sprintf_spec_double_with_minus);
  tcase_add_test(tc1_2, sprintf_spec_string_with_width_space);
  tcase_add_test(tc1_2, sprintf_spec_string_with_width_and_minus);
  tcase_add_test(tc1_2, sprintf_spec_double_minus_25);
  tcase_add_test(tc1_2, sprintf_spec_int_minus_zero);
  tcase_add_test(tc1_2, sprintf_anya);
  tcase_add_test(tc1_2, octal);
  tcase_add_test(tc1_2, octal_width);
  tcase_add_test(tc1_2, octal_width_minus);
  tcase_add_test(tc1_2, octal_width_zero);
  tcase_add_test(tc1_2, hex);
  tcase_add_test(tc1_2, hex_width);
  tcase_add_test(tc1_2, hex_width_minus);
  tcase_add_test(tc1_2, hex_width_zero);
  tcase_add_test(tc1_2, hexX);
  tcase_add_test(tc1_2, hexX_width);
  tcase_add_test(tc1_2, hexX_width_minus);
  tcase_add_test(tc1_2, hexX_width_zero);
  tcase_add_test(tc1_2, int_with_l);
  tcase_add_test(tc1_2, string);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
